Redux with React components ⚛️🔬
rmrmrmr/Bookstore pull request #7
Opened 2023-01-25 22:45 UTC by rmrmrmr

## On this pull request we:

- Added three books to the initial state 📖
- Applied inmutability to redux reducers 🧪

2023-01-25 23:03 UTC, zieeco requested changes
Hi @rmrmrmr ,


Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-25 23:03 UTC, zieeco commented on src/redux/books/books.js
>  };
### FORM

- Please, your form gets submitted when the input is empty this makes users add empty content and it gets added to the book. Kindly ensure the form is not submitted on the empty input field to improve your app's user experience.

2023-01-25 23:03 UTC, zieeco commented on src/redux/books/books.js
>  };
### README 

- Please, let's use the currently updated readme [template](https://github.com/microverseinc/readme-template) to update our readme so it is consistent with the new one also kindly remove all the placeholder text as they're there to guide you on how to update and add your personal content.

2023-01-26 01:01 UTC, BregornOriginal approved these changes
## Hi @rmrmrmr 

## Your project is complete!  There is nothing else to say other than... it's time to merge it 

## Congratulations! 

![giphy (1)](https://user-images.githubusercontent.com/93630700/214731453-a6348b5b-7db0-4586-b104-2ebd2544ca5a.gif)

## Highlights

✅ Good Pull request description
✅ Good work making the changes requested by previous reviewer 💯 

## Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.
Cheers and Happy coding!:aplauso::aplauso::aplauso:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, remember to tag me in your question so I can receive the notification.
------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)[.](https://airtable.com/shrQAqnBwek5a0O0s)._)

2023-01-26 01:02 UTC, merged